export const GET_POSTS_REQUEST = "GET_POSTS_REQUEST"
export const GET_POSTS_FAILURE = "GET_POSTS_FAILURE"
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS"

export const POST_POSTS_REQUEST = "POST_POSTS_REQUEST"
export const POST_POSTS_FAILURE = "POST_POSTS_FAILURE"
export const POST_POSTS_SUCCESS = "POST_POSTS_SUCCESS"


export const GET_POST_REQUEST = "GET_POST_REQUEST"
export const GET_POST_FAILURE = "GET_POST_FAILURE"
export const GET_POST_SUCCESS = "GET_POST_SUCCESS"
