export const GET_COMMENT_REQUEST = "GET_COMMENT_REQUEST"
export const GET_COMMENT_FAILURE = "GET_COMMENT_FAILURE"
export const GET_COMMENT_SUCCESS = "GET_COMMENT_SUCCESS"

export const POST_COMMENT_REQUEST = "POST_COMMENT_REQUEST"
export const POST_COMMENT_FAILURE = "POST_COMMENT_FAILURE"
export const POST_COMMENT_SUCCESS = "POST_COMMENT_SUCCESS"
